# Generated by Django 5.2.10 on 2026-01-30 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('persona_id', models.IntegerField(primary_key=True, serialize=False)),
                ('youtuber_name', models.CharField(max_length=10)),
            ],
        ),
    ]
