<<<<<<< HEAD
# Generated by Django 5.2.10 on 2026-01-30 01:04
=======
# Generated by Django 6.0.1 on 2026-01-29 06:27
>>>>>>> 4eb589572afb66703ad4c12d5eb3277ca8cda87e

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='nickname',
            new_name='name',
        ),
    ]
